# Generated by Django 5.1.4 on 2026-03-09 08:42

import files.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=files.models.upload_to)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('uploader_name', models.CharField(blank=True, default='Anonymous', max_length=100)),
                ('message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
